<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-06-26 17:53:18                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoTypeDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'type';
		}
		
		public function getObjectName()
		{
			return 'Type';
		}
		
		public function getSequence()
		{
			return 'type_id';
		}
		
		public function uncacheLists()
		{
			Item::dao()->uncacheLists();
			
			return parent::uncacheLists();
		}
	}
?>