<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-06-26 17:53:18                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoItemDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'item';
		}
		
		public function getObjectName()
		{
			return 'Item';
		}
		
		public function getSequence()
		{
			return 'item_id';
		}
	}
?>