<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-06-25 23:41:38                         *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoUserDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'user';
		}
		
		public function getObjectName()
		{
			return 'User';
		}
		
		public function getSequence()
		{
			return 'user_id';
		}
	}
?>