<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-06-28 11:04:08                         *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoSaleDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'sale';
		}
		
		public function getObjectName()
		{
			return 'Sale';
		}
		
		public function getSequence()
		{
			return 'sale_id';
		}
	}
?>