<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-06-25 23:41:38                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class UserDAO extends AutoUserDAO
	{
		// last chance for customization
	}
?>