<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-06-28 11:04:08                         *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoItem extends NamedObject
	{
		protected $description = null;
		protected $type = null;
		protected $price = null;
		protected $sale = null;
		protected $saleId = null;
		
		public function getDescription()
		{
			return $this->description;
		}
		
		/**
		 * @return Item
		**/
		public function setDescription($description)
		{
			$this->description = $description;
			
			return $this;
		}
		
		/**
		 * @return Type
		**/
		public function getType()
		{
			return $this->type;
		}
		
		/**
		 * @return Item
		**/
		public function setType(Type $type)
		{
			$this->type = $type;
			
			return $this;
		}
		
		/**
		 * @return Item
		**/
		public function dropType()
		{
			$this->type = null;
			
			return $this;
		}
		
		public function getPrice()
		{
			return $this->price;
		}
		
		/**
		 * @return Item
		**/
		public function setPrice($price)
		{
			$this->price = $price;
			
			return $this;
		}
		
		/**
		 * @return Sale
		**/
		public function getSale()
		{
			if (!$this->sale && $this->saleId) {
				$this->sale = Sale::dao()->getById($this->saleId);
			}
			
			return $this->sale;
		}
		
		public function getSaleId()
		{
			return $this->saleId;
		}
		
		/**
		 * @return Item
		**/
		public function setSale(Sale $sale)
		{
			$this->sale = $sale;
			$this->saleId = $sale->getId();
			
			return $this;
		}
		
		/**
		 * @return Item
		**/
		public function setSaleId($id)
		{
			$this->sale = null;
			$this->saleId = $id;
			
			return $this;
		}
		
		/**
		 * @return Item
		**/
		public function dropSale()
		{
			$this->sale = null;
			$this->saleId = null;
			
			return $this;
		}
	}
?>