<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-06-26 17:53:18                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class Item extends AutoItem implements Prototyped, DAOConnected
	{
		/**
		 * @return Item
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return ItemDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('ItemDAO');
		}
		
		/**
		 * @return ProtoItem
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoItem');
		}
		
		// your brilliant stuff goes here
	}
?>